type Factory @entity(immutable: false) {
  id: ID!
  address: Bytes!
  bookTemplateAddress: Bytes!
  shelfTemplateAddress: Bytes!
  collectionTemplateAddress: Bytes!
  tokenAddress: Bytes!
  adminAddress: Bytes!
  treasuryAddress: Bytes!
  paymentToken: ERC20Token!
  upgradeFee: BigInt!
  bookCount: Int!
}

type ERC20Token @entity(immutable: true) {
  id: ID!
  name: String!
  symbol: String!
  decimals: Int!
}

type BookToken @entity(immutable: false) {
  id: ID!
  network: Int!
  book: Book!
  tokenId: BigInt!
  tokenAddress: Bytes!
  details: BookTokenMetadata!
  detailsURL: String!
  owners: [User!]!
}

type BookTokenMetadata @entity(immutable: true) {
  id: ID!
  name: String
  description: String
  image: String
  animationURL: String
  externalURL: String
  mimeType: String
}

type Book @entity(immutable: false) {
  id: ID!
  network: Int!
  paused: Boolean!
  address: Bytes!
  factory: Factory!
  numCompletedUsers: Int!
  completedUsers: [User!]!
  numUsers: Int!
  users: [User!]!
  owners: [User!]!
  admins: [User!]!
  reviewers: [User!]!
  editors: [User!]!
  creator: User!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  editedBy: User
  editedAt: Timestamp
  creationTxHash: Bytes!
  details: BookMetadata
  detailsURL: String
  chaptersPassed: [ChapterStatus!]!
  chaptersFailed: [ChapterStatus!]!
  chaptersInReview: [ChapterStatus!]!
  chapterCount: Int! # includes number of chapters which are not paused
  totalChapterCount: Int! # includes all chapters
  chapters: [Chapter!]! @derivedFrom(field: "book")
  edits: [BookEdit!]! @derivedFrom(field: "book")
  status: [ChapterStatus!]! @derivedFrom(field: "book")
  submittedProofs: [ProofSubmission!]! @derivedFrom(field: "book")
  submittedReviews: [ReviewSubmission!]! @derivedFrom(field: "book")
  token: BookToken! @derivedFrom(field: "book")
  version: String!
  premium: Boolean!
}

type BookMetadata @entity(immutable: true) {
  id: ID!
  name: String
  description: String
  image: String
  externalURL: String
  slug: String
  categories: [Category!]
  book: Book! @derivedFrom(field: "details")
}

type Category @entity(immutable: true) {
  id: ID!
  name: String!
}

type BookEdit @entity(immutable: true) {
  id: ID!
  book: Book!
  editor: User!
  timestamp: Timestamp!
  txHash: Bytes!
  details: BookMetadata
  detailsURL: String
}

type Chapter @entity(immutable: false) {
  id: ID!
  optional: Boolean!
  skipReview: Boolean!
  paused: Boolean!
  book: Book!
  chapterId: BigInt!
  numCompletedUsers: Int!
  completedUsers: [User!]!
  numUsers: Int!
  users: [User!]!
  details: ChapterMetadata!
  detailsURL: String!
  creator: User!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  editedBy: User
  editedAt: Timestamp
  creationTxHash: Bytes!
  usersPassed: [ChapterStatus!]!
  usersFailed: [ChapterStatus!]!
  usersInReview: [ChapterStatus!]!
  status: [ChapterStatus!]! @derivedFrom(field: "chapter")
  edits: [ChapterEdit!]! @derivedFrom(field: "chapter")
  submittedProofs: [ProofSubmission!]! @derivedFrom(field: "chapter")
  submittedReviews: [ReviewSubmission!]! @derivedFrom(field: "chapter")
}

type _Schema_
  @fulltext(
    name: "chapterSearch"
    language: en
    algorithm: proximityRank
    include: [
      {
        entity: "ChapterMetadata",
        fields: [
          { name: "name" },
          { name: "description" }
        ]
      },
    ]
  )
  @fulltext(
    name: "bookSearch"
    language: en
    algorithm: proximityRank
    include: [
      {
        entity: "BookMetadata",
        fields: [
          { name: "name" },
          { name: "description" }
        ]
      },
    ]
  )
  @fulltext(
    name: "shelfSearch"
    language: en
    algorithm: proximityRank
    include: [
      {
        entity: "ShelfMetadata",
        fields: [
          { name: "name" },
          { name: "description" }
        ]
      },
    ]
  )
  @fulltext(
    name: "collectionSearch"
    language: en
    algorithm: proximityRank
    include: [
      {
        entity: "CollectionMetadata",
        fields: [
          { name: "name" },
          { name: "description" }
        ]
      },
    ]
  )

type ChapterMetadata @entity(immutable: true) {
  id: ID!
  chapter: Chapter! @derivedFrom(field: "details")
  name: String
  description: String
  image: String
  externalURL: String
}

type ChapterEdit @entity(immutable: true) {
  id: ID!
  chapter: Chapter!
  editor: User!
  timestamp: Timestamp!
  txHash: Bytes!
  details: ChapterMetadata!
  detailsURL: String!
}

type User @entity(immutable: false) {
  id: Bytes!
  chaptersPassed: [ChapterStatus!]!
  chaptersFailed: [ChapterStatus!]!
  chaptersInReview: [ChapterStatus!]!
  chapterEdits: [ChapterEdit!]! @derivedFrom(field: "editor")
  ownerOf: [Book!]! @derivedFrom(field: "owners")
  adminOf: [Book!]! @derivedFrom(field: "admins")
  editorOf: [Book!]! @derivedFrom(field: "editors")
  reviewerOf: [Book!]! @derivedFrom(field: "reviewers")
  status: [ChapterStatus!]! @derivedFrom(field: "user")
  submittedProofs: [ProofSubmission!]! @derivedFrom(field: "user")
  submittedReviews: [ReviewSubmission!]! @derivedFrom(field: "reviewer")
  tokens: [BookToken!]! @derivedFrom(field: "owners")
  completedChapters: [Chapter!]! @derivedFrom(field: "completedUsers")
  completedBooks: [Book!]! @derivedFrom(field: "completedUsers")
}

enum Status {
  init
  review
  pass
  fail
}

type ChapterStatus @entity(immutable: false) {
  id: ID!
  chapter: Chapter!
  book: Book!
  user: User!
  status: Status!
  updatedAt: Timestamp!
  submissions: [ProofSubmission!]!
  reviews: [ReviewSubmission!]! @derivedFrom(field: "chapterStatus")
}

type ProofSubmission @entity(immutable: false) {
  id: ID!
  chapter: Chapter!
  book: Book!
  chapterStatus: ChapterStatus!
  user: User!
  details: SubmissionMetadata!
  detailsURL: String!
  timestamp: Timestamp!
  txHash: Bytes!
}

type SubmissionMetadata @entity(immutable: true) {
  id: ID!
  name: String
  description: String
  image: String
  externalURL: String
}

type ReviewSubmission @entity(immutable: false) {
  id: ID!
  chapter: Chapter!
  book: Book!
  chapterStatus: ChapterStatus!
  proof: ProofSubmission
  accepted: Boolean!
  user: User!
  reviewer: User!
  details: SubmissionMetadata!
  detailsURL: String!
  timestamp: Timestamp!
  txHash: Bytes!
}

type Shelf @entity(immutable: false) {
  id: ID!
  network: Int!
  tokenId: BigInt! @unique
  address: Bytes!
  factory: Factory!
  creator: User!
  admins: [User!]!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  creationTxHash: Bytes!
  details: ShelfMetadata
  detailsURL: String
  contents: [Book!]
}

type ShelfMetadata @entity(immutable: true) {
  id: ID!
  name: String
  description: String
  cover: String
  slug: String
  categories: [Category!]
  shelf: Shelf! @derivedFrom(field: "details")
}

type Collection @entity(immutable: false) {
  id: ID!
  network: Int!
  address: Bytes!
  factory: Factory!
  creator: User!
  admins: [User!]!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  creationTxHash: Bytes!
  details: CollectionMetadata
  detailsURL: String
  contents: [Shelf!]
}

type CollectionMetadata @entity(immutable: true) {
  id: ID!
  name: String
  description: String
  cover: String
  slug: String
  categories: [Category!]
  collection: Collection! @derivedFrom(field: "details")
}
